### ISSUE TITLE
Fix custom filters when mention bot username

### ISSUE THREAD

**Issue by yasirarism** [Divkix/Alita_Robot#179]
## Checklist
- [✓] I am sure the error is coming from Bot's code and not elsewhere.
- [✓] I have searched in the issue tracker for similar bug reports, including closed ones.
- [✓] I ran `pip3 install -U https://github.com/DivideProjects/Alita_Robot/archive/master.zip` and reproduced the issue using the latest development version.
- [✓] I'n not here to spam and show that I'm stupid.

## Description
A clear and concise description of the problem.
What is happening?
Why do you think it is happening?
https://github.com/DivideProjects/Alita_Robot/blob/e01f4f691c5bc531f1ff4630032adcd4e0c9382c/alita/utils/custom_filters.py#L67
Fix this regex command because when use command example with /command@bn bot will respond, it must not respond because not valid command only respond with valid bot username. And make case sensitive command too.

## Traceback
The full traceback (if applicable)

**Comment by annihilatorrrr** [comment]
ok

**Comment by Divkix** [comment]
Thanks for opening the issue, this issue is because the Pyrogram library doesn't support this feature yet, as on the latest PyPi build [v1.2.9](https://pypi.org/project/Pyrogram/1.2.9/)
I have applied a fix [here](https://github.com/DivideProjects/Alita_Robot/blob/improvision/alita/utils/custom_filters.py#L36-L114)

**Comment by annihilatorrrr** [comment]
Done.
